version: "3"
services:
  controller:
    container_name: jenkins-controller
    image: jenkins/jenkins:2.383-jdk11
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
