= AsciiDocとHugoでホームページを作成する
:source-highlighter: rouge
:toc:
:experimental:
:hugo-develop-site-url: http://localhost:1313/

技術情報を発信するブログを作成したいので，AsciiDocとHugoで手軽に作ってみる。

== 環境

* OS: Windows 10 Home 21H2
* WSL: Ubuntu 18.04.6 LTS
* Docker: Docker Desktop 4.12.0

本書中のコマンドはUbuntu on WSLで実行する。

== とりあえずHugoを使ってみる

AsciiDoctorがインストールされたHugoのDockerイメージを使用する。

Hugo shellを起動する。
このシェルではbashのコマンドが使用できる。

[source, bash]
----
docker compose -p hugo-test run --rm --service-ports hugo shell
----

``docker-compose.yml``でカレントディレクトリをコンテナ内の``src``にマウントするよう指定しているので，ホストOS側でファイルを編集すれば，コンテナ内でも反映される。

HugoのQuick Start<<hugo-quick-start>>に従い操作してみる。

[[create-sample-hugo-site]]
Hugoサイトを作成する footnote:[https://gohugo.io/getting-started/quick-start/#commands] 。

[source, bash, subs="attributes+"]
----
# サイトの雛型を作成
hugo new site quickstart
# プロジェクトのルートディレクトリに移動
cd quickstart
git init
# Anankeテーマをダウンロードして配置
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
# ダウンロードしたテーマを使用することをサイトの設定ファイルに追記
echo "theme = 'ananke'" >> config.toml
# Hugoの開発用Webサーバを起動
hugo server --baseURL {hugo-develop-site-url}
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，作成したページにアクセスできる。

== Webページを作成してみる

<<write-blog-with-asciidoc-and-hugo-1, この記事>>を参考に，Webページを作成してみる。

以降は<<create-sample-hugo-site, Quick Startで作成した>>``/src/quickstart``ディレクトリ内で作業する。

[[create-template]]
=== テンプレートを作成する

以下のファイルを``archetypes``に配置する。

[source, adoc]
.default.adoc
--------
---
title: ""
date: "{{ dateFormat "2006-01-02" .Date }}"
lastmod: "{{ dateFormat "2006-01-02" .Date }}"
draft: true
slug: ""
thumbnail: ""
description: ""
tags: []
isCJKLanguage: true
archives: ["{{ dateFormat "2006/01" .Date }}"]
---
--------

``---``で囲われた領域はフロントマター<<hugo-front-matter>>で，ここで各ページのプロパティを指定する。

=== ページを作成する

``hugo new``コマンドで新しいページを作成する。

[source, bash]
----
hugo new posts/sample.adoc
----

上記のコマンドにより，``content/posts/``内に``sample.adoc``が生成される。
このファイルには，<<create-template>>で作成したテンプレートが適用されている。

=== サイト全体の設定

``config.toml``を次のとおり編集する。

[source, toml]
.config.toml
----
# サイトトップに表示されるタイトル
title = "Sample"

# 使用するテーマ
# themesディレクトリに同名のディレクトリがないとエラーになる
theme = "beautifulhugo"

# 日本語を含む場合の言語まわりの設定
defaultContentLanguage = "ja"
languageCode = "ja"
hasCJKLanguage= true
----

=== 開発用Webサーバを起動

以下のコマンドで開発用のWebサーバを起動する。

[source, bash, subs="attributes+"]
----
# -w: Hugoシェルを起動するコンテナ内のディレクトリを指定
#   Docker Composeファイルでホストのカレントディレクトリを
#   コンテナの"/src"にマウントするよう指定しているので，
#   結果としてホストの"quickstart"ディレクトリが使用される
docker compose -p hugo-test \
  run --rm \
  --service-ports \
  -w /src/quickstart \
  hugo \
  shell

# 開発用のWebサーバを起動
# -D: "draft: true"のファイルも生成対象とする
hugo server -D --baseURL {hugo-develop-site-url}
----

ただし，AsciiDocファイルからページを生成するとき，以下のようにエラーが出力されてしまう。

[source, bash]
----
Error: Error building site: "/src/quickstart/content/posts/sample.adoc:1:1": access denied: "asciidoctor" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
----

このため，``config.toml``に以下を追記して<<configure-hugo-security-exec-list>>から再度Webサーバを起動する。

[source, toml]
----
# "asciidoctor"コマンドを実行を許可するコマンドのリストに追加する。
# AsciiDocファイルからページを生成するときに，
# デフォルトの設定だと"asciidoctor"コマンドがリストに登録されておらずエラーになる。
[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，サイトのトップページにアクセスできる。

``hugo server``コマンドはファイルの更新を検知して自動的にページを更新してくれるはずだが，ホスト側のファイルをコンテナにマウントしているからか，ホスト側でファイルを更新してもページが更新されない。
``--poll``オプションを使用すると，指定した間隔でファイルの更新を確認するので，これで代用することができる。
ただしディスクへの負荷は高くなりそう。

[source, bash]
----
# ファイルが更新されているか1秒ごとに確認する
hugo server -D --poll 1s
----

-> Windowsのファイルシステムにファイルを配置していると上記のとおりだが，WSL内にファイルを配置すれば更新を検知してくれる。パフォーマンスの観点からもファイルはWSL内に配置するのが望ましい footnote:[https://learn.microsoft.com/ja-jp/windows/wsl/filesystems#file-storage-and-performance-across-file-systems[ファイル システム間での作業 | Microsoft Learn]]。

=== 使用するテーマを変更する

ここでは https://github.com/halogenica/beautifulhugo[beautifulhugo] に変更してみる。

. テーマを``themes``ディレクトリに配置する
+
[source, bash]
----
git submodule add https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
----
+
. サイト全体の設定を編集する
+
[source, diff]
----
--- a/config.toml
+++ b/config.toml
@@ -6 +6 @@ title = "Sample"
-theme = "ananke"
+theme = "beautifulhugo"
----

以降はページを生成すると変更後のテーマが使用される。

=== タグ一覧のページを作成する

参考

* https://maku77.github.io/hugo/taxonomy/basic.html[タクソノミーの基本 - まくまくHugoノート]
* https://www.yuyagishita.com/tech/hugo/config-setup/[Hugoで作成したサイトの表示設定について - YAGI BLOG]

``config.toml``に以下を追記する。

[source, toml]
.config.toml
----
[taxonomies]
tag = "tags"

[[menu.main]]
name = "タグ一覧"
url = "tags"
----

ページの上部に表示されるヘッダー部に，「タグ一覧」という名前でタグ一覧のページへのリンクが表示される。

=== ページに画像を挿入する

画像ファイルを管理する方法は2つある<<hugo-page-bundles>><<maku77-hugo-page-bundles>>。

1. 記事ファイルを``content``ディレクトリに，画像ファイルを``static``ファイルに配置する
+
....
content/
  |- 記事1.adoc
  |- 記事2.adoc
static/
  |- image1.png
  |- image2.png
....
+
2. 記事ファイルと画像ファイルを格納するフォルダを作成し，記事ファイルを``index.adoc``という名前で配置する
+
....
content/
  |- 記事1/
  |   |- index.adoc
  |   |- image1.png
  |- 記事2/
      |- index.adoc
      |- image2.png
....

2番の方法のほうが管理しやすい。

=== 作図

参考: https://gohugo.io/content-management/formats/[Content Formats | Hugo]

=== コンテンツの折り畳み

以下のように記載すると，コンテンツを折り畳むことができる。
クリックすることで展開したり再度折り畳んだりできる。

[source, asciidoc]
----
.折り畳み時に表示する見出し
[%collapsible]
====
折りたたみたいコンテンツ
====
----

ただし，"beautifulhugo"テーマに適用されるCSSだと，折り畳まれていることがわかるような記号などが表示されない。

=== 記事の作成および更新日時

フロントマターの``date``と``lastmod``で記事の作成および更新日時を指定できる。
ただし，未来の日時を指定するとページが生成されない。

Hugoの実行環境として使用しているDockerコンテナは，タイムゾーンがUTCに設定されているため，日本時間に変更しないと最新のページが生成されない。

Dockerコンテナが使用しているOSであるAlpine Linuxでタイムゾーンを日本時間に設定する手順は https://sebenkyo.com/2021/08/12/post-2203/[Alpine LinuxのタイムゾーンをAsia/Tokyoに変更する | SEのプログラミングと英語の勉強ブログ] を参照。
なお，既に``Dockerfile/Dockerfile``はタイムゾーンを日本時間に変更するよう実装している。

=== 目次を生成する

==== Hugoの設定ファイルを編集

``config.toml``の``[markup]``セクションに以下を追加する<<hugo-toc>>。

[source, toml]
.config.toml
----
include::./my-blog/config.toml[tag=table-of-contents]
----

==== Hugoのテーマを編集

``[サイトのルートディレクトリ]/layout``以下に``theme``と同じ構成でファイルを配置すると，ページを生成するときにこのファイルで``theme``以下のファイルを上書きして使用してくれる。

参考:

* https://shunyaueta.com/posts/2021-10-06/[Hugo で記事の更新日をgitと連携して自動的に取得して表示させる | hurutoriya]
* https://blog.chick-p.work/blog/hugo-site-directory[HUGO のディレクトリ構成 | ひよこまめ]

テーマのリポジトリ内の``layouts\_default\single.html``を，サイトのルートディレクトリ直下に``layouts\_default\single.html``としてコピーする。

サイトのルートディレクトリ直下の``layouts\_default\single.html``を開き、目次を表示したい箇所に次のように``{{ .TableOfContents }}``を追加する<<hugo-toc>>。

[source, html]
----
<h2>目次</h2>
{{ .TableOfContents }}
----

==== AsciiDocファイルにTOCディレクティブを追加

HugoはAsciiDocのTOCディレクティブに対応しているので，AsciiDocファイルでは``toc``アトリビュートを定義すればよい<<table-of-contents-with-asciidoc>>。
ただし``toclevels``アトリビュートの値は少なくとも``config.toml``の``[markup.tableOfContents.endLevel]``と等しい値である必要がある。

=== ソースコードをハイライトする

**TODO** RougeでハイライトするにはCSSを出力して配置する必要があるっぽい？

最新のAsciidoctorはRougeをサポートしている footnote:[<https://github.com/asciidoctor/asciidoctor/blob/main/CHANGELOG.adoc#200-2019-03-22---mojavelinux>] ので，``[markup.asciidocExt.extensions]``で``asciidoctor-rouge``を指定する必要がない。

== 新しいページを作成する手順

=== 新しいページを追加

. vscodeのタスク"start hugo shell"を実行
  * kbd:[F1] -> "Tasks: Run Task" -> "start hugo shell"を選択する
. 以下のコマンドを実行
+
[source, bash]
----
# 新しいページを追加
hugo new posts/<記事を格納するディレクトリ>/index.adoc
# コンテナから出る
exit
# コンテナ内で作成したファイルは所有者がrootになっていて
# コンテナ外から編集できないので，所有者を変更する
sudo chown -R <ユーザ名> <記事を格納するディレクトリ>
----

=== ページを編集

上記で作成した `index.adoc` を編集する。

=== 記事をプレビュー

. vscodeのタスク"start hugo server"を実行
. webブラウザで http://localhost:1313/ にアクセス

ファイルを保存すると，webブラウザで表示したページが自動的にリロードされる。

== 生成したページをGitHub Pagesで公開する

ここでは https://docs.github.com/ja/pages/getting-started-with-github-pages[GitHub Pages] を利用して，生成したページを公開する。

GitHub PagesでWebページを公開する手順は， https://prog-8.com/docs/github-pages[自分で作ったWebページをインターネット上に公開しよう！ | プログラミングの入門なら基礎から学べるProgate[プロゲート]] が参考になる。

. GitHubで``<アカウント名>.github.io``という名前のリポジトリを作成する。

. ``my-blog/config.toml``のトップレベルのセクションで，``baseurl``に``pass:[https://<上記のリポジトリ名>]``を指定する。
+
[source, toml]
.config.toml
----
baseurl = "https://[GitHubのアカウント名].github.io./"
----
+
. vscodeのタスク"run hugo"を実行してページを生成する
. ``my-blog/public/``にページを構成するファイルが生成される。このディレクトリをGitリポジトリとして初期化およびコミットする。
+
[source, bash]
----
cd my-blog/public
git init
git add -A
git commit
----
+
. 作成したリモートリポジトリにpushする。
+
[source, bash]
----
git remote add origin <リモートリポジトリのURL>
# GitHub Pagesで使用されるデフォルトのブランチは"main"なので，
# ローカルのブランチ名が異なる場合は変更する。
git branch -M main
git push -u origin main
----
+
. pushしたらページが公開されるまで数分待つ。
. ``++https://<GitHubのアカウント名>.github.io./++``にアクセスすると，pushしたサイトにアクセスできる。

以降は記事を更新するたびに，ページの生成，コミット，pushを実施すればよい。

[appendix]
== 付録

=== Git BashでDockerコマンド実行時にルートディレクトリから始まるパスを指定すると"working directory ... invalid"になる

Git Bashで，Dockerコマンドで``docker run -w /src``のようにルートディレクトリから始まるパスを指定して実行すると，以下のようにエラーが発生する。

[source, bash]
----
Error response from daemon: the working directory '["git-bash.exe"のパス]/src/' is invalid, it needs to be an absolute path
----

Git Bashは，WindowsのファイルパスをPOSIX形式に変換する機能がある。
上記のエラーは，この機能により``/src``がGit Bashのルートディレクトリからの相対パスに変換されたために発生している。

これを回避するためのワークアラウンドとして，パスの先頭を``//``にすればよい。
例えば``/src``は``//src``とする。

参考

* https://github.com/docker/cli/issues/2204#issuecomment-638993192
* https://qiita.com/nannany_stores/items/52c471d7b13bff9b285e[WindowsのGit Bashでパス変換が予期せぬ動作をする場合の対処法 - Qiita]
* https://qiita.com/KoyaChan/items/6db4ee5f444fbdeb7a35[git bashで docker -w /usr/src/projectが失敗 - Qiita]

=== vscodeのタスク機能で開発用のHugoサーバを起動する

開発用のHugoサーバを起動するためにコマンドを入力するのは手間なので，vscodeのタスク機能にこの手順を登録する。

``.vscode/tasks.json``に以下を記述する。

[source, bash]
..vscode/tasks.json
----
include::.vscode/tasks.json[]
----
* ``${workspaceFolder}``はタスク実行時にワークスペースのルートディレクトリへの絶対パスに置換される。

タスクを実行するには， kbd:[F1] -> _タスク: タスクの実行(Tasks: Run task)_ -> 実行するタスクを選択する。

[bibliography]
== 参考文献

* [[[write-blog-with-asciidoc-and-hugo-1, 1]]] https://deankh.github.io/blog/posts/dwjnjn8tbf/[Hugo + AsciidocでGitHub Pages上にブログを公開するまで その1 - DeanKHの日記]
* [[[hugo-quick-start, 2]]] https://gohugo.io/getting-started/quick-start/[Quick Start | Hugo]
* [[[hugo-front-matter, 3]]] https://gohugo.io/content-management/front-matter/[Front Matter | Hugo]
* [[[configure-hugo-security-exec-list, 4]]] https://stackoverflow.com/questions/71058236/hugo-with-asciidoctor[blogs - Hugo with Asciidoctor - Stack Overflow]
* [[[table-of-contents-with-asciidoc, 5]]] https://gohugo.io/content-management/toc/#usage-with-asciidoc[Table of Contents | Hugo]
* [[[hugo-toc, 6]]] https://note.mokuzine.net/hugo-toc/[hugoで目次(tableOfContents)を表示する方法]
* [[[hugo-page-bundles, 7]]] https://gohugo.io/content-management/page-bundles/[Page Bundles | Hugo]
* [[[maku77-hugo-page-bundles, 8]]] https://maku77.github.io/hugo/misc/page-bundle.html[画像ファイルを Markdown ファイルと同じディレクトリに置く (Page Bundle) - まくまくHugoノート]
* [[[github-pages, 9]]] https://docs.github.com/ja/pages/getting-started-with-github-pages[GitHub Pages の概要 - GitHub Docs]
