= AsciiDocとHugoでホームページを作成する
:source-highlighter: rouge
:toc:
:hugo-develop-site-url: http://localhost:1313/

技術情報を発信するブログを作成したいので，AsciiDocとHugoで手軽に作ってみる。

== 環境

* OS: Windows 10 Home 21H2
* WSL: Ubuntu 18.04.6 LTS
* Docker: Docker Desktop 4.12.0

本書中のコマンドはUbuntu on WSLで実行する。

== とりあえずHugoを使ってみる

AsciiDoctorがインストールされたHugoのDockerイメージを使用する。

Hugo shellを起動する。
このシェルではbashのコマンドが使用できる。

[source, bash]
----
docker compose -p hugo-test run --rm --service-ports hugo shell
----

``docker-compose.yml``でカレントディレクトリをコンテナ内の``src``にマウントするよう指定しているので，ホストOS側でファイルを編集すれば，コンテナ内でも反映される。

HugoのQuick Start<<hugo-quick-start>>に従い操作してみる。

[[create-sample-hugo-site]]
Hugoサイトを作成する footnote:[https://gohugo.io/getting-started/quick-start/#commands] 。

[source, bash]
----
# サイトの雛型を作成
hugo new site quickstart
# プロジェクトのルートディレクトリに移動
cd quickstart
git init
# Anankeテーマをダウンロードして配置
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
# ダウンロードしたテーマを使用することをサイトの設定ファイルに追記
echo "theme = 'ananke'" >> config.toml
# Hugoの開発用Webサーバを起動
hugo server
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，作成したページにアクセスできる。

== Webページを作成してみる

<<write-blog-with-asciidoc-and-hugo-1, この記事>>を参考に，Webページを作成してみる。

以降は<<create-sample-hugo-site, Quick Startで作成した>>``/src/quickstart``ディレクトリ内で作業する。

[[create-template]]
=== テンプレートを作成する

以下のファイルを``archetypes``に配置する。

[source, adoc]
.default.adoc
--------
---
title: ""
date: "{{ dateFormat "2006-01-02" .Date }}"
lastmod: "{{ dateFormat "2006-01-02" .Date }}"
draft: true
slug: ""
thumbnail: ""
description: ""
tags: []
isCJKLanguage: true
archives: ["{{ dateFormat "2006/01" .Date }}"]
---
--------

``---``で囲われた領域はフロントマター<<hugo-front-matter>>で，ここで各ページのプロパティを指定する。

=== ページを作成する

``hugo new``コマンドで新しいページを作成する。

[source, bash]
----
hugo new posts/sample.adoc
----

上記のコマンドにより，``content/posts/``内に``sample.adoc``が生成される。
このファイルには，<<create-template>>で作成したテンプレートが適用されている。

=== サイト全体の設定

``config.toml``を次のとおり編集する。

[source, toml]
.config.toml
----
# サイトトップに表示されるタイトル
title = "Sample"

# 使用するテーマ
# themesディレクトリに同名のディレクトリがないとエラーになる
theme = "beautifulhugo"

# 日本語を含む場合の言語まわりの設定
defaultContentLanguage = "ja"
languageCode = "ja"
hasCJKLanguage= true
----

=== 開発用Webサーバを起動

以下のコマンドで開発用のWebサーバを起動する。

[source, bash]
----
# -w: Hugoシェルを起動するコンテナ内のディレクトリを指定
#   Docker Composeファイルでホストのカレントディレクトリを
#   コンテナの"/src"にマウントするよう指定しているので，
#   結果としてホストの"quickstart"ディレクトリが使用される
docker compose -p hugo-test \
  run --rm \
  --service-ports \
  -w /src/quickstart \
  hugo \
  shell

# 開発用のWebサーバを起動
# -D: "draft: true"のファイルも生成対象とする
hugo server -D
----

ただし，AsciiDocファイルからページを生成するとき，以下のようにエラーが出力されてしまう。

[source, bash]
----
Error: Error building site: "/src/quickstart/content/posts/sample.adoc:1:1": access denied: "asciidoctor" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
----

このため，``config.toml``に以下を追記して<<configure-hugo-security-exec-list>>から再度Webサーバを起動する。

[source, toml]
----
# "asciidoctor"コマンドを実行を許可するコマンドのリストに追加する。
# AsciiDocファイルからページを生成するときに，
# デフォルトの設定だと"asciidoctor"コマンドがリストに登録されておらずエラーになる。
[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，サイトのトップページにアクセスできる。

``hugo server``コマンドはファイルの更新を検知して自動的にページを更新してくれるはずだが，ホスト側のファイルをコンテナにマウントしているからか，ホスト側でファイルを更新してもページが更新されない。
``--poll``オプションを使用すると，指定した間隔でファイルの更新を確認するので，これで代用することができる。
ただしディスクへの負荷は高くなりそう。

[source, bash]
----
# ファイルが更新されているか1秒ごとに確認する
hugo server -D --poll 1s
----

=== 使用するテーマを変更する

ここでは https://github.com/halogenica/beautifulhugo[beautifulhugo] に変更してみる。

. テーマを``themes``ディレクトリに配置する
+
[source, bash]
----
git submodule add https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
----
+
. サイト全体の設定を編集する
+
[source, diff]
----
--- a/config.toml
+++ b/config.toml
@@ -6 +6 @@ title = "Sample"
-theme = "ananke"
+theme = "beautifulhugo"
----

以降はページを生成すると変更後のテーマが使用される。

=== タグ一覧のページを作成する

参考

* https://maku77.github.io/hugo/taxonomy/basic.html[タクソノミーの基本 - まくまくHugoノート]
* https://www.yuyagishita.com/tech/hugo/config-setup/[Hugoで作成したサイトの表示設定について - YAGI BLOG]

``config.toml``に以下を追記する。

[source, toml]
.config.toml
----
[taxonomies]
tag = "tags"

[[menu.main]]
name = "タグ一覧"
url = "tags"
----

ページの上部に表示されるヘッダー部に，「タグ一覧」という名前でタグ一覧のページへのリンクが表示される。

=== ページに画像を挿入する

画像ファイルを管理する方法は2つある<<hugo-page-bundles>><<maku77-hugo-page-bundles>>。

1. 記事ファイルを``content``ディレクトリに，画像ファイルを``static``ファイルに配置する
+
....
content/
  |- 記事1.adoc
  |- 記事2.adoc
static/
  |- image1.png
  |- image2.png
....
+
2. 記事ファイルと画像ファイルを格納するフォルダを作成し，記事ファイルを``index.adoc``という名前で配置する
+
....
content/
  |- 記事1/
  |   |- index.adoc
  |   |- image1.png
  |- 記事2/
      |- index.adoc
      |- image2.png
....

2番の方法のほうが管理しやすい。

=== 作図

参考: https://gohugo.io/content-management/formats/[Content Formats | Hugo]

=== コンテンツの折り畳み

以下のように記載すると，コンテンツを折り畳むことができる。
クリックすることで展開したり再度折り畳んだりできる。

[source, asciidoc]
----
.折り畳み時に表示する見出し
[%collapsible]
====
折りたたみたいコンテンツ
====
----

ただし，"beautifulhugo"テーマに適用されるCSSだと，折り畳まれていることがわかるような記号などが表示されない。

=== 記事の作成および更新日時

フロントマターの``date``と``lastmod``で記事の作成および更新日時を指定できる。
ただし，未来の日時を指定するとページが生成されない。

Hugoの実行環境として使用しているDockerコンテナは，タイムゾーンがUTCに設定されているため，日本時間に変更しないと最新のページが生成されない。

Dockerコンテナが使用しているOSであるAlpine Linuxでタイムゾーンを日本時間に設定する手順は https://sebenkyo.com/2021/08/12/post-2203/[Alpine LinuxのタイムゾーンをAsia/Tokyoに変更する | SEのプログラミングと英語の勉強ブログ] を参照。
なお，既に``Dockerfile/Dockerfile``はタイムゾーンを日本時間に変更するよう実装している。

=== 目次を生成する

==== Hugoの設定ファイルを編集

``config.toml``の``[markup]``セクションに以下を追加する<<hugo-toc>>。

[source, toml]
.config.toml
----
include::./my-blog/config.toml[tag=table-of-contents]
----

==== Hugoのテーマを編集

テーマファイルへ``{{ .TableOfContents }}``を追加する<<hugo-toc>>。

``layouts\_default\single.html``を開き、目次を表示したい箇所に次のようなコードを追加する。

[source, html]
----
<h2>目次</h2>
{{ .TableOfContents }}
----

==== AsciiDocファイルにTOCディレクティブを追加

HugoはAsciiDocのTOCディレクティブに対応しているので，AsciiDocファイルでは``toc``アトリビュートを定義すればよい<<table-of-contents-with-asciidoc>>。
ただし``toclevels``アトリビュートの値は少なくとも``config.toml``の``[markup.tableOfContents.endLevel]``と等しい値である必要がある。

== 生成したページをGitHub Pagesで公開する

ここでは https://docs.github.com/ja/pages/getting-started-with-github-pages[GitHub Pages] を利用して，生成したページを公開する。

GitHub PagesでWebページを公開する手順は， https://prog-8.com/docs/github-pages[自分で作ったWebページをインターネット上に公開しよう！ | プログラミングの入門なら基礎から学べるProgate[プロゲート]] が参考になる。

. GitHubで``<アカウント名>.github.io``という名前のリポジトリを作成する。

. ``my-blog/config.toml``のトップレベルのセクションで，``baseurl``に``pass:[https://<上記のリポジトリ名>]``を指定する。
+
[source, toml]
.config.toml
----
baseurl = "https://[GitHubのアカウント名].github.io./"
----
+
. 以下のコマンドでページを生成する。
+
[source, bash]
----
docker compose -p hugo-test run --rm -w /src/my-blog hugo
----
+
. ``my-blog/public/``にページを構成するファイルが生成される。このディレクトリをGitリポジトリとして初期化およびコミットする。
+
[source, bash]
----
cd my-blog/public
git init
git add -A
git commit
----
+
. 作成したリモートリポジトリにpushする。
+
[source, bash]
----
git remote add origin <リモートリポジトリのURL>
# GitHub Pagesで使用されるデフォルトのブランチは"main"なので，
# ローカルのブランチ名が異なる場合は変更する。
git branch -M main
git push -u origin main
----
+
. pushしたらページが公開されるまで数分待つ。
. ``++https://<GitHubのアカウント名>.github.io./++``にアクセスすると，pushしたサイトにアクセスできる。

以降は記事を更新するたびに，ページの生成，コミット，pushを実施すればよい。


[bibliography]
== 参考文献

* [[[write-blog-with-asciidoc-and-hugo-1, 1]]] https://deankh.github.io/blog/posts/dwjnjn8tbf/[Hugo + AsciidocでGitHub Pages上にブログを公開するまで その1 - DeanKHの日記]
* [[[hugo-quick-start, 2]]] https://gohugo.io/getting-started/quick-start/[Quick Start | Hugo]
* [[[hugo-front-matter, 3]]] https://gohugo.io/content-management/front-matter/[Front Matter | Hugo]
* [[[configure-hugo-security-exec-list, 4]]] https://stackoverflow.com/questions/71058236/hugo-with-asciidoctor[blogs - Hugo with Asciidoctor - Stack Overflow]
* [[[table-of-contents-with-asciidoc, 5]]] https://gohugo.io/content-management/toc/#usage-with-asciidoc[Table of Contents | Hugo]
* [[[hugo-toc, 6]]] https://note.mokuzine.net/hugo-toc/[hugoで目次(tableOfContents)を表示する方法]
* [[[hugo-page-bundles, 7]]] https://gohugo.io/content-management/page-bundles/[Page Bundles | Hugo]
* [[[maku77-hugo-page-bundles, 8]]] https://maku77.github.io/hugo/misc/page-bundle.html[画像ファイルを Markdown ファイルと同じディレクトリに置く (Page Bundle) - まくまくHugoノート]
* [[[github-pages, 9]]] https://docs.github.com/ja/pages/getting-started-with-github-pages[GitHub Pages の概要 - GitHub Docs]
