= AsciiDocとHugoでホームページを作成する
:source-highlighter: rouge
:toc:
:hugo-develop-site-url: http://localhost:1313/

技術情報を発信するブログを作成したいので，AsciiDocとHugoで手軽に作ってみる。

== 環境

* OS: Windows 10 Home 21H2
* WSL: Ubuntu 18.04.6 LTS
* Docker: Docker Desktop 4.12.0

本書中のコマンドはUbuntu on WSLで実行する。

== とりあえずHugoを使ってみる

AsciiDoctorがインストールされたHugoのDockerイメージを使用する。

Hugo shellを起動する。
このシェルではbashのコマンドが使用できる。

[source, bash]
----
docker compose -p hugo-test run --service-ports hugo
----

``docker-compose.yml``でカレントディレクトリをコンテナ内の``src``にマウントするよう指定しているので，ホストOS側でファイルを編集すれば，コンテナ内でも反映される。

HugoのQuick Start<<hugo-quick-start>>に従い操作してみる。

[[create-sample-hugo-site]]
Hugoサイトを作成する footnote:[https://gohugo.io/getting-started/quick-start/#commands] 。

[source, bash]
----
# サイトの雛型を作成
hugo new site quickstart
# プロジェクトのルートディレクトリに移動
cd quickstart
git init
# Anankeテーマをダウンロードして配置
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
# ダウンロードしたテーマを使用することをサイトの設定ファイルに追記
echo "theme = 'ananke'" >> config.toml
# Hugoの開発用Webサーバを起動
hugo server
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，作成したページにアクセスできる。

== Webページを作成してみる

<<write-blog-with-asciidoc-and-hugo-1, この記事>>を参考に，Webページを作成してみる。

以降は<<create-sample-hugo-site, Quick Startで作成した>>``/src/quickstart``ディレクトリ内で作業する。

[[create-template]]
=== テンプレートを作成する

以下のファイルを``archetypes``に配置する。

[source, adoc]
.default.adoc
----
include::quickstart/archetypes/default.adoc[]
----

``---``で囲われた領域はフロントマター<<hugo-front-matter>>で，ここで各ページのプロパティを指定する。

=== ページを作成する

``hugo new``コマンドで新しいページを作成する。

[source, bash]
----
hugo new posts/sample.adoc
----

上記のコマンドにより，``content/posts/``内に``sample.adoc``が生成される。
このファイルには，<<create-template>>で作成したテンプレートが適用されている。

=== サイト全体の設定

``config.toml``を次のとおり編集する。

[source, toml]
.config.toml
----
include::quickstart/config.toml[tag=base-config]
----

=== 開発用Webサーバを起動

以下のコマンドで開発用のWebサーバを起動する。

[source, bash]
----
# -D: "draft: true"のファイルも生成対象とする
hugo server -D
----

ただし，AsciiDocファイルからページを生成するとき，以下のようにエラーが出力されてしまう。

[source, bash]
----
Error: Error building site: "/src/quickstart/content/posts/sample.adoc:1:1": access denied: "asciidoctor" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
----

このため，``config.toml``に以下を追記して<<configure-hugo-security-exec-list>>から再度Webサーバを起動する。

[source, toml]
----
include::quickstart/config.toml[tag=security-config]
----

Webブラウザで {hugo-develop-site-url} にアクセスすると，サイトのトップページにアクセスできる。

``hugo server``コマンドはファイルの更新を検知して自動的にページを更新してくれるはずだが，ホスト側のファイルをコンテナにマウントしているからか，ホスト側でファイルを更新してもページが更新されない。
``--poll``オプションを使用すると，指定した間隔でファイルの更新を確認するので，これで代用することができる。
ただしディスクへの負荷は高くなりそう。

[source, bash]
----
# ファイルが更新されているか1秒ごとに確認する
hugo server -D --poll 1s
----

=== 使用するテーマを変更する

ここでは https://github.com/halogenica/beautifulhugo[beautifulhugo] に変更してみる。

. テーマを``themes``ディレクトリに配置する
+
[source, bash]
----
git submodule add https://github.com/halogenica/beautifulhugo.git themes/beautifulhugo
----
+
. サイト全体の設定を編集する
+
[source, diff]
----
--- a/config.toml
+++ b/config.toml
@@ -6 +6 @@ title = "Sample"
-theme = "ananke"
+theme = "beautifulhugo"
----

以降はページを生成すると変更後のテーマが使用される。

=== タグ一覧のページを作成する

参考

* https://maku77.github.io/hugo/taxonomy/basic.html[タクソノミーの基本 - まくまくHugoノート]
* https://www.yuyagishita.com/tech/hugo/config-setup/[Hugoで作成したサイトの表示設定について - YAGI BLOG]

``config.toml``に以下を追記する。

[source, toml]
.config.toml
----
include::quickstart/config.toml[tag=add-tag-list-page]
----

ページの上部に表示されるヘッダー部に，「タグ一覧」という名前でタグ一覧のページへのリンクが表示される。

=== ページに画像を挿入する

画像ファイルを管理する方法は2つある。

1. 記事ファイルを``content``ディレクトリに，画像ファイルを``static``ファイルに配置する
+
....
content/
  |- 記事1.adoc
  |- 記事2.adoc
static/
  |- image1.png
  |- image2.png
....
+
2. 記事ファイルと画像ファイルを格納するフォルダを作成し，記事ファイルを``index.adoc``という名前で配置する
+
....
content/
  |- 記事1/
  |   |- index.adoc
  |   |- image1.png
  |- 記事2
      |- index.adoc
      |- image2.png
....

2番の方法のほうが管理しやすい。

[bibliography]
== 参考文献

* [[[write-blog-with-asciidoc-and-hugo-1, 1]]] https://deankh.github.io/blog/posts/dwjnjn8tbf/[Hugo + AsciidocでGitHub Pages上にブログを公開するまで その1 - DeanKHの日記]
* [[[hugo-quick-start, 2]]] https://gohugo.io/getting-started/quick-start/[Quick Start | Hugo]
* [[[hugo-front-matter, 3]]] https://gohugo.io/content-management/front-matter/[Front Matter | Hugo]
* [[[configure-hugo-security-exec-list, 4]]] https://stackoverflow.com/questions/71058236/hugo-with-asciidoctor[blogs - Hugo with Asciidoctor - Stack Overflow]
