version: "3"

# Jenkinsのコントローラとエージェントが
# Gitリポジトリにアクセスできる必要があるので，
# ネットワークに接続する
networks:
  external:
    name: jenkins_default
    external: true

volumes:
  gitea:
    driver: local

services:
  server:
    image: gitea/gitea:1.17.3
    container_name: gitea
    restart: "no"
    networks:
      - external
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
