# サイトトップに表示されるタイトル
title = "備忘録"

# ルートディレクトリのURLを指定する。
# 各ページのURLは"baseurl"からの相対パスとして設定される。
# これが未設定だと，結果的にページ内で使用するcssやjavascriptのファイルへのパスが
# そのページからの相対パスになってしまうため，
# ルートディレクトリ直下のファイルを参照できなくなる。
# baseurl = "http://localhost:8000"
baseurl = "https://niinumatoshitaka.github.io./"

# 使用するテーマ
# themesディレクトリに同名のディレクトリがないとエラーになる
theme = "beautifulhugo"

# 日本語を含む場合の言語まわりの設定
defaultContentLanguage = "ja"
languageCode = "ja"
hasCJKLanguage= true

[Params]
description = "ソフトウェアエンジニアの備忘録です。"
# "Highlight.js"を使用して，クライアントサイドでコードをハイライトする
useHLJS = true

# "asciidoctor"コマンドを実行を許可するコマンドのリストに追加する。
# AsciiDocファイルからページを生成するときに，
# デフォルトの設定だと"asciidoctor"コマンドがリストに登録されておらずエラーになる。
[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]

[taxonomies]
tag = "tags"

[[menu.main]]
name = "タグ一覧"
url = "tags"

[markup]
  # AsciiDocファイルに対する設定
  [markup.asciidocExt]
    # 使用する拡張機能を指定
    # hugoの実行環境に指定した拡張機能がインストールされている必要がある
    extensions = ["asciidoctor-diagram"]
    trace = true
    verbose = true
    # asciidoctor-diagramを使用するには，この値がtrueである必要がある
    workingFolderCurrent = true
  
  # tag::table-of-contents[]
  [markup.tableOfContents]
    # 目次を生成するhタグ（<h2>, <h3>など）のレベルを指定
    startLevel = 2
    endLevel = 3
    # <ol>タグで生成するか<ul>タグで生成するかを指定
    ordered = false
  # end::table-of-contents[]

  [markup.asciidocExt.attributes]
    figure-caption = "図"
    sectnums = ""
    sectlinks = ""
